export class MyInvestment {
    documents: [];
    investmentNo: number;
    investorName: string;
    amountInvested: number;
    transferDate: Date;
    transactionFrom: string;
    transactionTo: string;
    transactionNo: string;
    profitMonthlyPct: number;
    profitMonthly: number;
    profitAnnualPct: number;
    profitAnnual: number;
    profitEndPct: number;
    profitEnd: number;
    investType: string;
    firstProfitDate: Date;
    lastProfitDate: Date;
    payBackDate: Date;
    torbenMonthlyPct: number;
    torbenMonthly: number;
    torbenAnnualPct: number;
    torbenAnnual: number;
    torbenEndPct: number;
    torbenEnd: number;
    description: string;
    createdDate: Date;
    createdBy: string;
    modifiedDate: Date;
    modifiedBy: string;
    startDate: null
}